# Generated by Django 4.0.3 on 2022-03-28 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0002_driver_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='bus_no',
            field=models.IntegerField(unique=True),
        ),
    ]
