# Generated by Django 4.0.3 on 2022-03-28 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0003_alter_bus_bus_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='driver_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='busapp.driver'),
        ),
    ]
