# Generated by Django 4.0.3 on 2022-03-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0004_alter_bus_driver_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='destination',
            field=models.CharField(choices=[('BANEPA', 'BANEPA'), ('SANGA', 'SANBA'), ('DHULIKHEL', 'DHULIKHEL'), ('RATNAPARK', 'RATNAPARK'), ('RNAC', 'RNAC'), ('KOTESHAWOR', 'KOTESHAWOR')], max_length=10),
        ),
    ]
