# Generated by Django 4.0.3 on 2022-03-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0005_alter_appointment_date_alter_bus_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
