# Generated by Django 4.0.3 on 2022-03-30 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0008_alter_appointment_seat_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(),
        ),
    ]
